version: '3.8'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_PASSWORD=guest"
      - "POSTGRES_USER=guest"
      - "POSTGRES_DB=search_demo"
